import { auth, db } from '../firebase-config.js';
import { doc, getDoc } from 'firebase/firestore';
import { getStorage, ref, uploadBytes } from 'firebase/storage';
const storage = getStorage(auth.app);
import { onAuthStateChanged } from 'firebase/auth';

const $=id=>document.getElementById(id); const form=$('reservationForm'), date=$('reservationDate'), time=$('reservationTime'), duration=$('reservationDuration');
const grids={standard:$('standardGrid'),premium:$('premiumGrid')}, counts={standard:$('standardCount'),premium:$('premiumCount')};
const selected=new Map(); let appConfig=null, rigs=[], currentUser=null, promos=[];
const wheel='https://firebasestorage.googleapis.com/v0/b/inerciaapp-e0cc4.firebasestorage.app/o/assets%2Ftimon.svg?alt=media&token=42e46a5a-59d8-450f-92df-104e7f891e49';
function money(n){return `L ${Number(n||0).toLocaleString('es-HN',{maximumFractionDigits:2})}`}
async function api(path,options={}){ const headers={...(options.headers||{})}; if(currentUser) headers.Authorization=`Bearer ${await currentUser.getIdToken()}`; if(options.body && !(options.body instanceof FormData)) headers['Content-Type']='application/json'; const r=await fetch(path,{...options,headers}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||'No se pudo completar la solicitud.'); return data; }
function dates(){ const fmt=new Intl.DateTimeFormat('es-HN',{weekday:'short',day:'numeric',month:'short',timeZone:'America/Tegucigalpa'}); for(let i=0;i<7;i++){const d=new Date(Date.now()+i*86400000); const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'America/Tegucigalpa'}).format(d); date.add(new Option(`${i===0?'HOY · ':i===1?'MAÑANA · ':''}${fmt.format(d)}`.toUpperCase(),parts));}}
function makeTimes(){ time.innerHTML='<option value="">Seleccioná una hora</option>'; if(!date.value||!appConfig)return; const day=new Date(`${date.value}T12:00:00Z`).getUTCDay(), h=appConfig.hours[day]; if(!h)return; const toMin=x=>{const[a,b]=x.split(':').map(Number);return a*60+b}; for(let m=toMin(h[0]);m<toMin(h[1]);m+=30){const hh=Math.floor(m/60),mm=m%60, v=`${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`, label=new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,hh,mm)); time.add(new Option(label,v));}}
function makeDurations(){duration.innerHTML='';for(let i=appConfig.minDurationHours;i<=appConfig.maxDurationHours;i++)duration.add(new Option(`${i} ${i===1?'hora':'horas'}`,i));}
async function loadConfig(){const d=await api(`/api/reservations/config?date=${encodeURIComponent(date.value||'')}`);appConfig=d.config;rigs=d.rigs;promos=d.promotions||[];makeDurations(); updatePrices(); render(rigs.map(r=>({...r,available:true})));}
function updatePrices(){document.querySelector('[data-price="standard"]')?.replaceChildren(document.createTextNode(`${money(appConfig?.prices.standard)} / HORA`));document.querySelector('[data-price="premium"]')?.replaceChildren(document.createTextNode(`${money(appConfig?.prices.premium)} / HORA`));}
function card(r){const b=document.createElement('button');b.type='button';b.className='simulator-card';b.disabled=!r.available;b.dataset.id=r.id;b.innerHTML=`<span class="simulator-check">✓</span><img class="simulator-wheel" src="${wheel}" alt=""><span class="simulator-card-info"><small>${r.type.toUpperCase()}</small><strong>SIMULADOR ${r.number}</strong></span>`;if(selected.has(r.id)&&r.available)b.classList.add('selected');b.onclick=()=>{selected.has(r.id)?selected.delete(r.id):selected.set(r.id,r);b.classList.toggle('selected',selected.has(r.id));summary()};return b;}
function render(list){for(const t of ['standard','premium']){grids[t].innerHTML='';const x=list.filter(r=>r.type===t);x.forEach(r=>grids[t].append(card(r)));const n=x.filter(r=>r.available).length;counts[t].textContent=`${n} DISPONIBLES`;} $('availableCount').textContent=list.filter(r=>r.available).length;summary();}
async function availability(){selected.clear(); if(!date.value||!time.value||!duration.value){render(rigs.map(r=>({...r,available:true})));return;} try{const d=await api(`/api/reservations/availability?date=${date.value}&time=${time.value}&duration=${duration.value}`);render(d.rigs);}catch(e){message(e.message,'error');render(rigs.map(r=>({...r,available:false})));}}
function localPrice(){const h=Number(duration.value||1);let base=0;for(const r of selected.values())base+=(Number(appConfig?.prices[r.type])||0)*h;let discount=0;for(const p of promos){if(p.type==='percent')discount+=base*(Number(p.value||0)/100);else if(p.type==='fixed')discount+=Number(p.value||0)}return Math.max(0,base-Math.min(base,discount));}
function summary(){$('summaryStandard').textContent=[...selected.values()].filter(x=>x.type==='standard').length;$('summaryPremium').textContent=[...selected.values()].filter(x=>x.type==='premium').length;$('summaryDuration').textContent=`${duration.value||1} ${Number(duration.value)===1?'hora':'horas'}`;$('reservationTotal').textContent=money(localPrice());$('reservationSubmit').disabled=!(currentUser&&date.value&&time.value&&selected.size);}
function message(text,type='info'){const el=$('reservationMessage');if(!el)return;el.textContent=text;el.dataset.type=type;el.hidden=!text;}
async function profile(user){const s=await getDoc(doc(db,'users',user.uid));const p=s.data()||{};$('reservationName').value=p.name||user.displayName||'';$('reservationEmail').value=p.email||user.email||'';$('reservationPhone').value=p.phoneNumber||'';}
onAuthStateChanged(auth,async u=>{currentUser=u;if(u)await profile(u);else message('Iniciá sesión para hacer una reserva.','error');summary();});
date.addEventListener('change',async()=>{makeTimes();selected.clear();await loadConfig();summary()}); time.addEventListener('change',availability); duration.addEventListener('change',availability);
document.querySelectorAll('input[name="payment"]').forEach(x=>x.addEventListener('change',()=>{$('proofBlock').hidden=document.querySelector('input[name="payment"]:checked')?.value!=='transferencia'}));
form.addEventListener('submit',async e=>{e.preventDefault(); if(!currentUser)return message('Iniciá sesión para continuar.','error'); const btn=$('reservationSubmit');btn.disabled=true;message('Procesando reserva…');try{let proofPath=null;const payment=document.querySelector('input[name="payment"]:checked')?.value;if(payment==='transferencia'){const file=$('paymentProof').files[0];if(!file)throw new Error('Subí el comprobante de transferencia.');if(file.size>5*1024*1024)throw new Error('El comprobante no puede pesar más de 5 MB.');if(!['image/jpeg','image/png','application/pdf'].includes(file.type))throw new Error('El comprobante debe ser JPG, PNG o PDF.');proofPath=`reservation-proofs/${currentUser.uid}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await uploadBytes(ref(storage,proofPath),file,{contentType:file.type});}
 const body={date:date.value,time:time.value,duration:Number(duration.value),rigIds:[...selected.keys()],payment,proofPath,customer:{name:$('reservationName').value.trim(),email:$('reservationEmail').value.trim(),phoneNumber:$('reservationPhone').value.trim()}};const r=await api('/api/reservations/create',{method:'POST',body:JSON.stringify(body)});message(`Reserva ${r.code} creada. Estado: PENDIENTE. Total: ${money(r.pricing.total)}.`,'success');selected.clear();await availability();}catch(err){message(err.message,'error');}finally{summary();}});
dates(); loadConfig().then(makeTimes).catch(e=>message(e.message,'error'));
