import { FieldValue } from 'firebase-admin/firestore';
import { method,json,fail,requireUser } from '../_lib/http.js';
import { adminDb,adminStorage } from '../_lib/firebase-admin.js';
import { getConfig,validateWhen,activePromotions,priceReservation,slotIds,code,expiresAt,bad } from '../_lib/reservations.js';
const METHODS=new Set(['transferencia','tarjeta']);
export default async function handler(req,res){ try{ if(!method(req,res,['POST']))return; const user=await requireUser(req); const b=req.body||{}; const config=await getConfig(); const when=validateWhen(b.date,b.time,b.duration,config); if(!Array.isArray(b.rigIds)||!b.rigIds.length||b.rigIds.length>10) throw bad('Seleccioná al menos un simulador válido.'); if(!METHODS.has(b.payment)) throw bad('Método de pago inválido.');
 const unique=[...new Set(b.rigIds.map(String))]; const rigRefs=unique.map(id=>adminDb.doc(`rigs/${id}`)); const rigDocs=await adminDb.getAll(...rigRefs); if(rigDocs.some(x=>!x.exists||x.data().active!==true)) throw bad('Uno de los simuladores ya no está disponible.'); const rigs=rigDocs.map(x=>({id:x.id,...x.data()}));
 const promos=await activePromotions(b.date,rigs.map(r=>r.type)); const pricing=priceReservation(rigs,Number(b.duration),config,promos,when.lead); const profile=await adminDb.doc(`users/${user.uid}`).get(); const p=profile.data()||{}; const customer={name:String(b.customer?.name||p.name||user.name||'').trim(),email:String(b.customer?.email||p.email||user.email||'').trim(),phoneNumber:String(b.customer?.phoneNumber||p.phoneNumber||'').trim()}; if(!customer.name||!customer.email||!customer.phoneNumber) throw bad('Completá nombre, correo y teléfono.');
 let proof=null; if(b.payment==='transferencia'){ if(!b.proofPath) throw bad('Subí el comprobante de transferencia.'); const prefix=`reservation-proofs/${user.uid}/`; if(!String(b.proofPath).startsWith(prefix)) throw bad('Comprobante inválido.'); const file=adminStorage.bucket().file(b.proofPath); const [exists]=await file.exists(); if(!exists) throw bad('No encontramos el comprobante subido.'); const [meta]=await file.getMetadata(); if(Number(meta.size)>5*1024*1024||!['image/jpeg','image/png','application/pdf'].includes(meta.contentType)) throw bad('El comprobante debe ser JPG, PNG o PDF y pesar máximo 5 MB.'); proof={path:b.proofPath,contentType:meta.contentType,size:Number(meta.size)}; }
 const reservationRef=adminDb.collection('reservations').doc(); const reservationCode=code(); const lockRefs=rigs.flatMap(r=>slotIds(b.date,when.start,when.end,config.slotMinutes,r.id).map(id=>adminDb.doc(`reservationLocks/${id}`)));
 await adminDb.runTransaction(async tx=>{ const lockDocs=lockRefs.length?await tx.getAll(...lockRefs):[]; if(lockDocs.some(x=>x.exists)) throw bad('Uno de esos simuladores acaba de ser reservado. Actualizá la disponibilidad.',409); for(const ref of lockRefs) tx.create(ref,{reservationId:reservationRef.id,uid:user.uid,expiresAt:expiresAt(b.date,b.time)}); tx.create(reservationRef,{code:reservationCode,uid:user.uid,customer,date:b.date,time:b.time,duration:Number(b.duration),rigs:rigs.map(r=>({id:r.id,type:r.type,number:r.number})),payment:b.payment,paymentProof:proof,pricing,promotionIds:promos.map(p=>p.id),status:'pending',createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()}); });
 await adminDb.doc(`users/${user.uid}`).set(customer,{merge:true}); json(res,201,{id:reservationRef.id,code:reservationCode,status:'pending',pricing});
 }catch(e){fail(res,e)} }
